export enum CONSUMING_FOOD_TYPE {
  RED_MEAT = "RED_MEAT",
  WHITE_MEAT = "WHITE_MEAT",
  FIST = "FIST",
  SEASON_FRUITS = "SEASON_FRUITS",
  EXOTIC_FRUITS = "EXOTIC_FRUITS",
  CHEESE = "CHEESE",
  RICE = "RICE",
  ALCOHOL = "ALCOHOL",
  SOFT = "SOFT",
}
