export enum HOME_CONSUMTION_TYPES {
  ELECTRICITY = "ELECTRICITY",
  NATURAL_GAS = "NATURAL_GAS",
  COAL = "COAL",
  HEATING_OIL = "HEATING_OIL",
  DRINK = "DRINK",
  HEAP_PUMP = "HEAP_PUMP",
  SOLAR_THERMAL = "SOLAR_THERMAL",
  URBAN_HEATING = "URBAN_HEATING",
  PROPAN = "PROPAN",
}
