name: CI

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: sudo apt-get install awscli -y
      - run: aws configure set ${{ secrets.CELLAR_ADDON_KEY_ID }}
      - run: aws configure set ${{ secrets.CELLAR_ADDON_KEY_SECRET }}
      - name: Deploy
        run: aws s3 sync ./dist s3://${{ secrets.CELLAR_ADDON_HOST }}