name: CI

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
      - run: aws --version
        shell: bash
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: export AWS_ACCESS_KEY_ID=${{ secrets.CELLAR_ADDON_KEY_ID }}
        shell: bash
      - run: export AWS_SECRET_ACCESS_KEY=${{ secrets.CELLAR_ADDON_KEY_SECRET }}
        shell: bash
      - name: Deploy
        run: aws s3 --endpoint-url https://${{ secrets.CELLAR_ADDON_HOST }} sync ./dist s3://${{ secrets.CELLAR_ADDON_HOST }}
        shell: bash